In [72]:
!pip install xlrd openpyxl
import os
import pandas as pd
import numpy as np
import xlrd as xl
import openpyxl as op
import datetime
from google.colab import drive, files
drive.mount('/content/drive')

Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **1er Punto**
Buscar la base de países del World Economic Outlook (WEO) del FMI, subirla a su Drive y cargarla en el notebook conectándose a Google Drive.

In [73]:
os.chdir('/content/drive/MyDrive/Colab Notebooks')

In [74]:
base = pd.read_excel("weoapr2025all.xlsx", sheet_name="weoapr2025all")

### Verificación

In [75]:
# Las primeras 5 filas
base.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,032.712","1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,-6240,2267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,283.442","1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,14501,17248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,86149,91272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0

In [76]:
# Las últimas 10 filas
base.tail(10)

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
8616,698,ZWE,GGXONLB_NGDP,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,Percent of GDP,Units,See notes for: General government primary net...,NaN,...,-4695,-5198,-1096,0.537,1529,1948,2028,2108,2108,2024.0
8617,698,ZWE,GGXWDN,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,National currency,Billions,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,698,ZWE,GGXWDN_NGDP,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,Percent of GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8619,698,ZWE,GGXWDG,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,4935,51682,557793,673344,739670,786902,862793,930773,993329,2024.0
8620,698,ZWE,GGXWDG_NGDP,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,Percent of GDP,Units,See notes for: General government gross debt ...,NaN,...,99536,96586,94587,58568,56051,53294,52315,50485,48312,2024.0
8621,698,ZWE,NGDP_FY,Zimbabwe,Gross domestic product corresponding to fiscal...,Gross domestic product corresponding to fiscal...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,4958,53509,589716,"1,149.685","1,319.643","1,476.529","1,649.212","1,843.656","2,056.061",2024.0
8622,698,ZWE,BCA,Zimbabwe,Current account balance,Current account is all transactions other than...,U.S. dollars,Billions,Source: Reserve Bank of Zimbabwe and Ministry ...,-0.301,...,0.305,0.135,0.505,1143,1210,1198,1226,1120,0.996,2023.0
8623,698,ZWE,BCA_NGDPD,Zimbabwe,Current account balance,Current account is all transactions other than...,Percent of GDP,Units,"See notes for: Gross domestic product, curren...",NaN,...,0.935,0.384,1435,2994,3063,2927,2895,2554,2196,2023.0
8624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8625,"International Monetary Fund, World Economic Ou...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
# 3 filas aleatorias
base.sample(3)

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
5682,142,NOR,NGDPRPC,Norway,"Gross domestic product per capita, constant pr...",GDP is expressed in constant national currency...,National currency,Units,"See notes for: Gross domestic product, consta...","529,775.630",...,"1,047,060.220","1,036,768.046","1,048,790.842","1,064,125.206","1,075,274.348","1,084,751.582","1,092,115.343","1,099,327.653","1,106,590.805",2024.0
6925,726,SOM,PCPIPCH,Somalia,"Inflation, average consumer prices",Annual percentages of average consumer prices ...,Percent change,Units,"See notes for: Inflation, average consumer pr...",NaN,...,6779,6173,5529,4600,4000,3400,3200,3000,2500,2023.0
7455,463,SYR,PCPIEPCH,Syria,"Inflation, end of period consumer prices",Annual percentages of end of period consumer p...,Percent change,Units,"See notes for: Inflation, end of period consu...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011.0

In [78]:
# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna.
base.iloc[2:6, [1]]

   ISO
2  AFG
3  AFG
4  AFG
5  AFG

In [79]:
# Use len() para saber cuántas filas tiene
len(base)

8626

In [80]:
# Use .shape para saber número de filas y columnas
base.shape

(8626, 61)

In [81]:
# Use .columns para ver el nombre de las columnas
base.columns

Index([             'WEO Country Code',                           'ISO',
                    'WEO Subject Code',                       'Country',
                  'Subject Descriptor',                 'Subject Notes',
                               'Units',                         'Scale',
       'Country/Series-specific Notes',                            1980,
                                  1981,                            1982,
                                  1983,                            1984,
                                  1985,                            1986,
                                  1987,                            1988,
                                  1989,                            1990,
                                  1991,                            1992,
                                  1993,                            1994,
                                  1995,                            1996,
                                  1997,                            1998,
                                  1999,                            2000,
                                  2001,                            2002,
                                  2003,                            2004,
                                  2005,                            2006,
                                  2007,                            2008,
                                  2009,                            2010,
                                  2011,                            2012,
                                  2013,                            2014,
                                  2015,                            2016,
                                  2017,                            2018,
                                  2019,                            2020,
                                  2021,                            2022,
                                  2023,                            2024,
                                  2025,                            2026,
                                  2027,                            2028,
                                  2029,                            2030,
               'Estimates Start After'],
      dtype='object')

In [82]:
# Use .dtypes para saber el tipo de dato de cada columna
base.dtypes

WEO Country Code          object
ISO                       object
WEO Subject Code          object
Country                   object
Subject Descriptor        object
                          ...
2027                      object
2028                      object
2029                      object
2030                      object
Estimates Start After    float64
Length: 61, dtype: object

In [83]:
# Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre columnas, tipos de datos y si hay valores nulos)
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 61 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WEO Country Code               8625 non-null   object
 1   ISO                            8624 non-null   object
 2   WEO Subject Code               8624 non-null   object
 3   Country                        8624 non-null   object
 4   Subject Descriptor             8624 non-null   object
 5   Subject Notes                  8624 non-null   object
 6   Units                          8624 non-null   object
 7   Scale                          8624 non-null   object
 8   Country/Series-specific Notes  7648 non-null   object
 9   1980                           3861 non-null   object
 10  1981                           3995 non-null   object
 11  1982                           4039 non-null   object
 12  1983                           4079 non-null   object
 13  1984                           4104 non-null   object
 14  1985                           4187 non-null   object
 15  1986                           4235 non-null   object
 16  1987                           4259 non-null   object
 17  1988                           4348 non-null   object
 18  1989                           4409 non-null   object
 19  1990                           4889 non-null   object
 20  1991                           5049 non-null   object
 21  1992                           5435 non-null   object
 22  1993                           5635 non-null   object
 23  1994                           5762 non-null   object
 24  1995                           6108 non-null   object
 25  1996                           6242 non-null   object
 26  1997                           6404 non-null   object
 27  1998                           6565 non-null   object
 28  1999                           6659 non-null   object
 29  2000                           7086 non-null   object
 30  2001                           7236 non-null   object
 31  2002                           7329 non-null   object
 32  2003                           7357 non-null   object
 33  2004                           7427 non-null   object
 34  2005                           7460 non-null   object
 35  2006                           7467 non-null   object
 36  2007                           7469 non-null   object
 37  2008                           7478 non-null   object
 38  2009                           7499 non-null   object
 39  2010                           7512 non-null   object
 40  2011                           7517 non-null   object
 41  2012                           7536 non-null   object
 42  2013                           7554 non-null   object
 43  2014                           7578 non-null   object
 44  2015                           7592 non-null   object
 45  2016                           7594 non-null   object
 46  2017                           7599 non-null   object
 47  2018                           7597 non-null   object
 48  2019                           7597 non-null   object
 49  2020                           7560 non-null   object
 50  2021                           7560 non-null   object
 51  2022                           7560 non-null   object
 52  2023                           7557 non-null   object
 53  2024                           7485 non-null   object
 54  2025                           7371 non-null   object
 55  2026                           7371 non-null   object
 56  2027                           7246 non-null   object
 57  2028                           7246 non-null   object
 58  2029                           7246 non-null   object
 59  2030                           7246 non-null   object
 60  Estimates Start After          7648 non-null   float64
dtypes: float64(1), object(60)
memory usage: 4.0+ MB

In [84]:
!pip install wbdata
import wbdata

Requirement already satisfied: wbdata in /usr/local/lib/python3.13/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.2)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.3.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

### **2do Punto**
Conectarse a la API del Banco Mundial y traer datos del PIB real para Estados Unidos, Alemania, Canadá, España, Francia e Italia, años 2010-2023.

In [85]:
pib = {"NY.GDP.PCAP.CD" : "pib real"}

fecha1 = datetime.datetime (2010,1,1)
fecha2 = datetime.datetime (2023,1,1)

base2 = wbdata.get_dataframe(pib , country=["USA", "CAN", "DEU", "ESP", "FRA", "ITA"], date=(fecha1, fecha2))

### Verificación

In [86]:
# Las primeras 5 filas
base2.head()

                  pib real
country date
Canada  2023  54847.537011
        2022  56496.927534
        2021  52886.640781
        2020  43537.898120
        2019  46352.969521

In [87]:
# Las últimas 10 filas
base2.tail(10)

                        pib real
country       date
United States 2019  65227.956591
              2018  62875.666138
              2017  60047.719073
              2016  57976.628204
              2015  56849.469792
              2014  55153.394018
              2013  53297.386290
              2012  51708.394061
              2011  50024.881232
              2010  48642.631209

In [88]:
# 3 filas aleatorias
base2.sample(3)

                  pib real
country date
Canada  2016  42314.103362
Spain   2020  27233.942646
        2014  29707.765509

In [89]:
# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna.
base2.iloc[2:6, [0]]

                  pib real
country date
Canada  2021  52886.640781
        2020  43537.898120
        2019  46352.969521
        2018  46539.217790

In [90]:
# Use len() para saber cuántas filas tiene
len(base2)

84

In [91]:
# Use .shape para saber número de filas y columnas
base2.shape

(84, 1)

In [92]:
# Use .columns para ver el nombre de las columnas
base2.columns

Index(['pib real'], dtype='object')

In [93]:
# Use .dtypes para saber el tipo de dato de cada columna
base2.dtypes

pib real    float64
dtype: object

In [94]:
# Use .info() para ver toda la información del conjunto de datos (número de filas, columnas,
# nombre columnas, tipos de datos y si hay valores nulos)
base2.info()

<class 'wbdata.client.DataFrame'>
MultiIndex: 84 entries, ('Canada', '2023') to ('United States', '2010')
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pib real  84 non-null     float64
dtypes: float64(1)
memory usage: 1.8+ KB

### **3er Punto**

Conectarse a la API del Banco Mundial y traer los siguientes datos para Brasil 2010-2023: crecimiento del PIB, PIB per cápita en PPA, tasa de inflación, tasa de desempleo y población.

In [95]:
indicadores = {"NY.GDP.MKTP.KD.ZG": "crecimiento pib",
               "NY.GDP.PCAP.PP.CD": "pib percapita en ppa",
               "FP.CPI.TOTL.ZG": "tasa de inflacion",
               "SL.UEM.TOTL.ZS": "tasa de desempleo",
               "SP.POP.TOTL": "poblacion"}

fecha3= datetime.datetime(2010,1,1)
fecha4= datetime.datetime(2023,1,1)

base3 = wbdata.get_dataframe(indicadores, country="BRA", date=(fecha3, fecha4))

### Verificación

In [96]:
# Las primeras 5 filas
base3.head()

,crecimiento pib,pib percapita en ppa,tasa de inflacion,tasa de desempleo,poblacion
date,,,,,
2023,3.241655,21193.072142,4.593563,7.947,211140729.0
2022,3.016694,19873.703262,9.280106,9.231,210306415.0
2021,4.762604,18075.706005,8.301660,13.158,209550294.0
2020,-3.276759,16101.618306,3.211768,13.697,208660842.0
2019,1.220778,16069.838015,3.732976,11.936,207455459.0

In [97]:
# Las últimas 10 filas
base3.tail(10)

,crecimiento pib,pib percapita en ppa,tasa de inflacion,tasa de desempleo,poblacion
date,,,,,
2019,1.220778,16069.838015,3.732976,11.936,207455459.0
2018,1.783667,15463.742639,3.664850,12.329,206107261.0
2017,1.322869,14559.048890,3.446373,12.792,204703445.0
2016,-3.275917,14309.206149,8.739144,11.580,203218114.0
2015,-3.545763,14821.438317,9.029901,8.538,201675532.0
2014,0.503956,15827.308163,6.329040,6.755,200085127.0
2013,3.004823,15722.333524,6.204311,7.071,198478299.0
2012,1.921176,15198.086331,5.403499,7.251,196876111.0
2011,3.974423,15211.792039,6.636450,7.578,195284734.0
2010,7.528226,14451.715838,5.038727,8.420,193701929.0

In [98]:
# 3 filas aleatorias
base3.sample(3)

,crecimiento pib,pib percapita en ppa,tasa de inflacion,tasa de desempleo,poblacion
date,,,,,
2020,-3.276759,16101.618306,3.211768,13.697,208660842.0
2017,1.322869,14559.048890,3.446373,12.792,204703445.0
2021,4.762604,18075.706005,8.301660,13.158,209550294.0

In [99]:
# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna.
base3.iloc[2:6, [1]]

      pib percapita en ppa
date
2021          18075.706005
2020          16101.618306
2019          16069.838015
2018          15463.742639

In [100]:
# Use len() para saber cuántas filas tiene
len(base3)

14

In [101]:
# Use .shape para saber número de filas y columnas
base3.shape

(14, 5)

In [102]:
# Use .columns para ver el nombre de las columnas
base3.columns

Index(['crecimiento pib', 'pib percapita en ppa', 'tasa de inflacion',
       'tasa de desempleo', 'poblacion'],
      dtype='object')

In [103]:
# Use .dtypes para saber el tipo de dato de cada columna
base3.dtypes

crecimiento pib         float64
pib percapita en ppa    float64
tasa de inflacion       float64
tasa de desempleo       float64
poblacion               float64
dtype: object

In [104]:
# Use .info() para ver toda la información del conjunto de datos (número de filas, columnas,
# nombre columnas, tipos de datos y si hay valores nulos)
base3.info()

<class 'wbdata.client.DataFrame'>
Index: 14 entries, 2023 to 2010
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   crecimiento pib       14 non-null     float64
 1   pib percapita en ppa  14 non-null     float64
 2   tasa de inflacion     14 non-null     float64
 3   tasa de desempleo     14 non-null     float64
 4   poblacion             14 non-null     float64
dtypes: float64(5)
memory usage: 672.0+ bytes

### **4to Punto**
Traer dos conjuntos de datos de la página de datos abiertos del Gobierno de Colombia utilizando API. Los que le llamen la atención

In [105]:
import requests

In [106]:
# Primer conjunto de datos
url = "https://www.datos.gov.co/resource/qijw-htwa.json"
response = requests.get(url)
data = response.json()
base4 = pd.DataFrame(data)

In [107]:
# Segundo conjunto de datos
url = "https://www.datos.gov.co/resource/22f3-gynv.json"
response = requests.get(url)
data = response.json()
base5 = pd.DataFrame(data)

### Verificación

In [108]:
from IPython.display import display

# Las primeras 5 filas
display(base4.head())

# Las últimas 10 filas
display(base4.tail(10))

# 3 filas aleatorias
display(base4.sample(3))

# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna
display(base4.iloc[2:6, [1]])

# Use len() para saber cuántas filas tiene
display(len(base4))

# Use .shape para saber número de filas y columnas
display(base4.shape)

# Use .columns para ver el nombre de las columnas
display(base4.columns)

# Use .dtypes para saber el tipo de dato de cada columna
display(base4.dtypes)

# Use .info() para ver toda la información del conjunto de datos
base4.info()

,a_o,secretaria,nombreestablecimiento,zona,direccion,telefono,codigo_etc,tipo_establecimiento,niveles,jornada,...,propiedad_planta_fisica,resguardo,matricula_contratada,calendario,correo_electronico,especialidad,discapacidades,etnias,estrato_socio_economico,modelos
0,2016,BOGOTA,GIMN NUEVO SIDAUTO ...,URBANA,KR 90 A 91 96,4366460 /2521545,LUZ ELENA GARZON,CENTRO EDUCATIVO,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,TARDE,FIN DE SEMANA",...,PERSONA NATURAL,NO APLICA,NO,A,1ºugimna@hotmail.com 1ºedugimna@hotmail.com ...,NaN,NaN,NaN,NaN,NaN
1,2016,BOGOTA,JARD INF LA CASITA DE CHENANO ...,URBANA,AV LAS AMERICAS 69 B 59,4177828,SOLANYI XIMENA FLORIAN CAMPOS,CENTRO EDUCATIVO,PREESCOLAR,COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,academchenano@gmail.com,NaN,NaN,NaN,NaN,NaN
2,2016,BOGOTA,ACADEMIA REAL PARA NIÑOS,URBANA,CL 42 A 87 I 10 SUR,4063716,YENNI MARCELA ROZO GARCIA,CENTRO EDUCATIVO,BÁSICA PRIMARIA,COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,academiareal2005@hotmail.com,NaN,NaN,NaN,NaN,NaN
3,2016,BOGOTA,COL BILING RICHMOND ...,URBANA,KR 53 222 76,6763865 -- 6763864 -- 6763866 -- 6763836 -- 67...,DIEGO FERNANDO SANCHEZ HURTADO,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,B,academica@cbr.edu.co --rectoria@cbr.edu.co,ACADÉMICA,NaN,NaN,NaN,NaN
4,2016,BOGOTA,COL COOP MONSEÑOR ISMAEL PERDOMO ...,URBANA,DG 62 G SUR 72 A 41,7764491 -- 7805045 -- 7784737,TULIO RAFAEL DE LA HOZ AMARIS,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,...,COOPERATIVO,NO APLICA,NO,A,academicacoop@etb.net.co,ACADÉMICA,NaN,NaN,NaN,NaN

,a_o,secretaria,nombreestablecimiento,zona,direccion,telefono,codigo_etc,tipo_establecimiento,niveles,jornada,...,propiedad_planta_fisica,resguardo,matricula_contratada,calendario,correo_electronico,especialidad,discapacidades,etnias,estrato_socio_economico,modelos
990,2016,BOGOTA,COLEGIO TECNISISTEMAS,URBANA,CL 72 65 25,3111762,ERNESTO PARRA HERRERA,CENTRO EDUCATIVO,"MEDIA,BÁSICA SECUNDARIA","MAÑANA,NOCTURNA,FIN DE SEMANA",...,PERSONA NATURAL,NO APLICA,NO,A,gerencia@institutotecnisistemas.com,ACADÉMICA,NaN,NaN,NaN,NaN
991,2016,BOGOTA,GIMN DE ENSEÑANZA LA SABANA ...,URBANA,CR. 65B NO. 61-20 SUR,2042612,SANDRA PATRICIA SARRIA RODRIGUEZ,CENTRO EDUCATIVO,PREESCOLAR,MAÑANA,...,PERSONA NATURAL,NO APLICA,NO,A,ges_saban@yahoo.com ...,NaN,"DI-COGNITIVO,SÍNDROME DE DOWN",NaN,NaN,NaN
992,2016,BOGOTA,GIMN GENERACION DEL FUTURO ...,URBANA,KR 114 152 D 63,6240917/ 6240918 /5386348,CLAUDIA FERNANDA PARRA CAMACHO,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,COMPLETA",...,PERSONA NATURAL,NO APLICA,NO,A,ggfuturo@hotmail.com generaciondelfuturo@hot...,ACADÉMICA,NaN,NaN,NaN,NaN
993,2016,BOGOTA,GIMN INF GUATIQUIA ...,URBANA,CL 59 A SUR 45 D 02,7151827,RUBIELA ANGEL GALVIS,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,COMPLETA,TARDE",...,PERSONA NATURAL,NO APLICA,NO,A,gguatiquia@gmail.com,ACADÉMICA,NaN,NaN,NaN,NaN
994,2016,BOGOTA,GIMN COLOMBIANO DEL SUR ...,URBANA,KR 23 63 A 15 SUR,7152732 / 7153603 ...,ABSALON CHAVERRA BERMUDEZ,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,gicosur@007mundo.com gicosur@etb.net.co ...,ACADÉMICA,NaN,NaN,NaN,NaN
995,2016,BOGOTA,GIMNASIO ACADEMICO AMOR BONDAD Y CIENCIA,URBANA,CL 127 D BIS 88 C 07,6817906 -- 3124572820,DAYRA INGRID GARZÓN SALAMANCA,CENTRO EDUCATIVO,PREESCOLAR,COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,gimabc2011@hotmail.com,NaN,NaN,NaN,NaN,NaN
996,2016,BOGOTA,GIMNASIO MATERNO INFANTIL CLAUDIA JESUS,URBANA,KR 94 H 83 19,4345780 -- 5350142,ALBA NELLY GUERRON VALLEJO,CENTRO EDUCATIVO,PREESCOLAR,MAÑANA,...,PERSONA NATURAL,NO APLICA,NO,A,gimainfclaje@hotmail.com,NaN,NaN,NaN,NaN,NaN
997,2016,BOGOTA,GIMNASIO MODERNO ALEXANDER SUTHERLAND,URBANA,CL 4 53 B 31,4948439,MONICA VIVIANA SUAREZ GOMEZ,CENTRO EDUCATIVO,"PREESCOLAR,BÁSICA PRIMARIA",COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,gimalsutherland05@hotmail.com,NaN,NaN,NaN,NaN,NaN
998,2016,BOGOTA,GIMN LOS ANDES ...,URBANA,AC 209 45 80,6761129,APOLINAR MENDOZA MUÑOZ,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,gimandes@gimandes.edu.co - leonordelgado2@yaho...,ACADÉMICA,NaN,NaN,NaN,NaN
999,2016,BOGOTA,GIMN MANOS UNIDAS ...,URBANA,CL 41 B SUR 3 A 62 ESTE,2061470 -- 3626577,MARGARITA DEL CARMEN ARDILA ALDANA,CENTRO EDUCATIVO,"PREESCOLAR,BÁSICA PRIMARIA",COMPLETA,...,PERSONA NATURAL,NO APLICA,NO,A,gimanosunidas@hotmail.com,NaN,MÚLTIPLE DISCAPACIDAD,NaN,NaN,NaN

,a_o,secretaria,nombreestablecimiento,zona,direccion,telefono,codigo_etc,tipo_establecimiento,niveles,jornada,...,propiedad_planta_fisica,resguardo,matricula_contratada,calendario,correo_electronico,especialidad,discapacidades,etnias,estrato_socio_economico,modelos
879,2016,BOGOTA,EL PORTAL FUNDACION,URBANA,IND AV. 13 NO.62-40 SUR (VÍA USME),2795778 / 7142246 / ...,MERCEDES BENAVIDES HERNANDEZ,CENTRO EDUCATIVO,"PREESCOLAR,BÁSICA PRIMARIA",COMPLETA,...,FUNDACION O CORPORACIONES,NO APLICA,SI,A,elportalfundacion@hotmail.com direccion@funda...,NaN,NaN,NaN,NaN,NaN
183,2016,BOGOTA,COLEGIO FRANCISCO JAVIER MATIZ (IED),URBANA,KR 3 29 28 SUR,2082080 -- 2082082,GLORIA PATRICIA REYES SALCEDO,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,TARDE",...,OFICIAL,NO APLICA,NO,A,cedfranciscojavie4@redp.edu.co,ACADÉMICA,"DI-COGNITIVO,LIMITACIÓN FISICA (MOVILIDAD),HIP...",NaN,NaN,NaN
927,2016,BOGOTA,COLEGIO ROBERT F. KENNEDY (IED),URBANA,AV BOYACA 64 H 39,2519559,JAIRO HERNAN TELLEZ SALAZAR,INSTITUCION EDUCATIVA,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,TARDE",...,OFICIAL,NO APLICA,NO,A,escdirobertkennedy10@redp.edu.co,ACADÉMICA,NaN,NaN,NaN,NaN

  secretaria
2     BOGOTA
3     BOGOTA
4     BOGOTA
5     BOGOTA

1000

(1000, 25)

Index(['a_o', 'secretaria', 'nombreestablecimiento', 'zona', 'direccion',
       'telefono', 'codigo_etc', 'tipo_establecimiento', 'niveles', 'jornada',
       'grados', 'modelos_educativos', 'idiomas', 'numero_de_sedes',
       'prestador_de_servicio', 'propiedad_planta_fisica', 'resguardo',
       'matricula_contratada', 'calendario', 'correo_electronico',
       'especialidad', 'discapacidades', 'etnias', 'estrato_socio_economico',
       'modelos'],
      dtype='object')

a_o                        object
secretaria                 object
nombreestablecimiento      object
zona                       object
direccion                  object
telefono                   object
codigo_etc                 object
tipo_establecimiento       object
niveles                    object
jornada                    object
grados                     object
modelos_educativos         object
idiomas                    object
numero_de_sedes            object
prestador_de_servicio      object
propiedad_planta_fisica    object
resguardo                  object
matricula_contratada       object
calendario                 object
correo_electronico         object
especialidad               object
discapacidades             object
etnias                     object
estrato_socio_economico    object
modelos                    object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   a_o                      1000 non-null   object
 1   secretaria               1000 non-null   object
 2   nombreestablecimiento    1000 non-null   object
 3   zona                     1000 non-null   object
 4   direccion                1000 non-null   object
 5   telefono                 990 non-null    object
 6   codigo_etc               1000 non-null   object
 7   tipo_establecimiento     1000 non-null   object
 8   niveles                  995 non-null    object
 9   jornada                  997 non-null    object
 10  grados                   995 non-null    object
 11  modelos_educativos       990 non-null    object
 12  idiomas                  262 non-null    object
 13  numero_de_sedes          1000 non-null   object
 14  prestador_de_servicio    1000 non-null   object
 15  propiedad_planta_fisica  1000 non-null   object
 16  resguardo                1000 non-null   object
 17  matricula_contratada     1000 non-null   object
 18  calendario               1000 non-null   object
 19  correo_electronico       1000 non-null   object
 20  especialidad             708 non-null    object
 21  discapacidades           222 non-null    object
 22  etnias                   25 non-null     object
 23  estrato_socio_economico  2 non-null      object
 24  modelos                  5 non-null      object
dtypes: object(25)
memory usage: 195.4+ KB

In [109]:
# Las primeras 5 filas
display(base5.head())

# Las últimas 10 filas
display(base5.tail(10))

# 3 filas aleatorias
display(base5.sample(3))

# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna
display(base5.iloc[2:6, [1]])

# Use len() para saber cuántas filas tiene
display(len(base5))

# Use .shape para saber número de filas y columnas
display(base5.shape)

# Use .columns para ver el nombre de las columnas
display(base5.columns)

# Use .dtypes para saber el tipo de dato de cada columna
display(base5.dtypes)

# Use .info() para ver toda la información del conjunto de datos
base5.info()

,anio,numeromes,nombremes,codigorubro,nombrerubro,niveluno,nombreniveluno,niveldos,nombreniveldos,niveltres,...,modificacionesaforo,aforovigente,saldocausado,recaudoefectivoperiodo,saldoacreedor,devolucionespagadasacumulado,recaudoefectivoacumulado,saldoaforoporrecaudar,recaudoefectivoacumuladoneto,nivel
0,2019,1,Enero,1-0-00-1-01-1-01,IMPUESTO SOBRE LA RENTA Y COMPLEMENTARIOS,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,0.00,0.00,0.00,8859748613178.00,0.00,5352020687.00,8859748613178.00,63150455000000.00,8854396592491.00,2
1,2019,1,Enero,1-0-00-1-01-1-01,IMPUESTO SOBRE LA RENTA Y COMPLEMENTARIOS,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,-1269622000000.00,63150455000000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
2,2019,1,Enero,1-0-00-1-01-1-01,IMPUESTO SOBRE LA RENTA Y COMPLEMENTARIOS,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,250000000000.00,0.00,2
3,2019,1,Enero,1-0-00-1-01-1-01,IMPUESTO SOBRE LA RENTA Y COMPLEMENTARIOS,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,0.00,250000000000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
4,2019,1,Enero,1-0-00-1-01-1-04,IMPUESTO PARA PRESERVAR LA SEGURIDAD DEMOCRÁTICA,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2

,anio,numeromes,nombremes,codigorubro,nombrerubro,niveluno,nombreniveluno,niveldos,nombreniveldos,niveltres,...,modificacionesaforo,aforovigente,saldocausado,recaudoefectivoperiodo,saldoacreedor,devolucionespagadasacumulado,recaudoefectivoacumulado,saldoaforoporrecaudar,recaudoefectivoacumuladoneto,nivel
990,2019,4,Abril,6-0-21,FONDO DE RECURSOS SOAT Y FONSAT (ANTES FOSYGA),6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,21,...,0.00,0.00,0.00,650360459768.93,0.00,0.00,650360459768.93,0.00,650360459768.93,2
991,2019,4,Abril,6-0-21,FONDO DE RECURSOS SOAT Y FONSAT (ANTES FOSYGA),6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,21,...,-738000000.00,1646200232000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
992,2019,4,Abril,6-0-22,FONDO DE SOLIDARIDAD PENSIONAL,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,22,...,0.00,0.00,0.00,244030281859.00,0.00,0.00,244030281859.00,0.00,244030281859.00,2
993,2019,4,Abril,6-0-22,FONDO DE SOLIDARIDAD PENSIONAL,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,22,...,0.00,1290105086223.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
994,2019,4,Abril,6-0-23,COMISION DE REGULACION DE TELECOMUNICACIONES,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,23,...,0.00,0.00,0.00,12051845782.22,0.00,0.00,12051845782.22,0.00,12051845782.22,2
995,2019,4,Abril,6-0-23,COMISION DE REGULACION DE TELECOMUNICACIONES,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,23,...,-2778000000.00,29339729924.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
996,2019,4,Abril,6-0-24,COMISION DE REGULACION DE ENERGIA Y GAS,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,24,...,0.00,0.00,0.00,11126910010.33,0.00,0.00,11126910010.33,0.00,11126910010.33,2
997,2019,4,Abril,6-0-24,COMISION DE REGULACION DE ENERGIA Y GAS,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,24,...,-4011632000.00,28015328300.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2
998,2019,4,Abril,6-0-25,COMISION DE REGULACION DE AGUA POTABLE,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,25,...,0.00,0.00,0.00,11014631507.00,0.00,3024500.00,11014631507.00,0.00,11011607007.00,2
999,2019,4,Abril,6-0-25,COMISION DE REGULACION DE AGUA POTABLE,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,25,...,0.00,17295277303.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2

,anio,numeromes,nombremes,codigorubro,nombrerubro,niveluno,nombreniveluno,niveldos,nombreniveldos,niveltres,...,modificacionesaforo,aforovigente,saldocausado,recaudoefectivoperiodo,saldoacreedor,devolucionespagadasacumulado,recaudoefectivoacumulado,saldoaforoporrecaudar,recaudoefectivoacumuladoneto,nivel
998,2019,4,Abril,6-0-25,COMISION DE REGULACION DE AGUA POTABLE,6,FONDOS ESPECIALES DE LA NACIÓN,0,FONDOS ESPECIALES DE LA NACIÓN,25,...,0.00,0.00,0.00,11014631507.00,0.00,3024500.00,11014631507.00,0.00,11011607007.00,2
340,2019,2,Febrero,2-0-00-2-14,OTROS RECURSOS DE CAPITAL,2,RECURSOS DE CAPITAL DE LA NACIÓN,0,RECURSOS DE CAPITAL DE LA NACIÓN,00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1781388535830.00,0.00,2
260,2019,2,Febrero,1-0-00-1-01-1-09,MONOTRIBUTO,1,INGRESOS CORRIENTES DE LA NACIÓN,0,INGRESOS CORRIENTES DE LA NACIÓN,00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2

  numeromes
2         1
3         1
4         1
5         1

1000

(1000, 40)

Index(['anio', 'numeromes', 'nombremes', 'codigorubro', 'nombrerubro',
       'niveluno', 'nombreniveluno', 'niveldos', 'nombreniveldos', 'niveltres',
       'nombreniveltres', 'nivelcuatro', 'nombrenivelcuatro', 'nivelcinco',
       'nombrenivelcinco', 'nivelseis', 'nombrenivelseis', 'nivelsiete',
       'nombrenivelsiete', 'nivelocho', 'nombrenivelocho', 'nivelnueve',
       'nombrenivelnueve', 'niveldiez', 'nombreniveldiez', 'codigofuente',
       'nombrefuente', 'codigosituacion', 'nombresituacion', 'aforoinicial',
       'modificacionesaforo', 'aforovigente', 'saldocausado',
       'recaudoefectivoperiodo', 'saldoacreedor',
       'devolucionespagadasacumulado', 'recaudoefectivoacumulado',
       'saldoaforoporrecaudar', 'recaudoefectivoacumuladoneto', 'nivel'],
      dtype='object')

anio                            object
numeromes                       object
nombremes                       object
codigorubro                     object
nombrerubro                     object
niveluno                        object
nombreniveluno                  object
niveldos                        object
nombreniveldos                  object
niveltres                       object
nombreniveltres                 object
nivelcuatro                     object
nombrenivelcuatro               object
nivelcinco                      object
nombrenivelcinco                object
nivelseis                       object
nombrenivelseis                 object
nivelsiete                      object
nombrenivelsiete                object
nivelocho                       object
nombrenivelocho                 object
nivelnueve                      object
nombrenivelnueve                object
niveldiez                       object
nombreniveldiez                 object
codigofuente                    object
nombrefuente                    object
codigosituacion                 object
nombresituacion                 object
aforoinicial                    object
modificacionesaforo             object
aforovigente                    object
saldocausado                    object
recaudoefectivoperiodo          object
saldoacreedor                   object
devolucionespagadasacumulado    object
recaudoefectivoacumulado        object
saldoaforoporrecaudar           object
recaudoefectivoacumuladoneto    object
nivel                           object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   anio                          1000 non-null   object
 1   numeromes                     1000 non-null   object
 2   nombremes                     1000 non-null   object
 3   codigorubro                   1000 non-null   object
 4   nombrerubro                   1000 non-null   object
 5   niveluno                      1000 non-null   object
 6   nombreniveluno                1000 non-null   object
 7   niveldos                      1000 non-null   object
 8   nombreniveldos                1000 non-null   object
 9   niveltres                     1000 non-null   object
 10  nombreniveltres               1000 non-null   object
 11  nivelcuatro                   1000 non-null   object
 12  nombrenivelcuatro             1000 non-null   object
 13  nivelcinco                    1000 non-null   object
 14  nombrenivelcinco              1000 non-null   object
 15  nivelseis                     1000 non-null   object
 16  nombrenivelseis               1000 non-null   object
 17  nivelsiete                    1000 non-null   object
 18  nombrenivelsiete              1000 non-null   object
 19  nivelocho                     1000 non-null   object
 20  nombrenivelocho               1000 non-null   object
 21  nivelnueve                    1000 non-null   object
 22  nombrenivelnueve              1000 non-null   object
 23  niveldiez                     1000 non-null   object
 24  nombreniveldiez               1000 non-null   object
 25  codigofuente                  1000 non-null   object
 26  nombrefuente                  1000 non-null   object
 27  codigosituacion               1000 non-null   object
 28  nombresituacion               1000 non-null   object
 29  aforoinicial                  1000 non-null   object
 30  modificacionesaforo           1000 non-null   object
 31  aforovigente                  1000 non-null   object
 32  saldocausado                  1000 non-null   object
 33  recaudoefectivoperiodo        1000 non-null   object
 34  saldoacreedor                 1000 non-null   object
 35  devolucionespagadasacumulado  1000 non-null   object
 36  recaudoefectivoacumulado      1000 non-null   object
 37  saldoaforoporrecaudar         1000 non-null   object
 38  recaudoefectivoacumuladoneto  1000 non-null   object
 39  nivel                         1000 non-null   object
dtypes: object(40)
memory usage: 312.6+ KB

### **5to Punto**
 Investigue otra página de donde pueda traer datos económicos o sociales mediante API y
cargue el conjunto de datos en el notebook.

In [110]:
# Install dependencies as needed:
!pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [111]:
# Instalar kagglehub y las dependencias necesarias
!pip install -q kagglehub[pandas-datasets]

# Importar librerías
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Nombre del archivo dentro del dataset
file_path = "btcusd_1-min_data.csv"

# Cargar el conjunto de datos desde Kaggle
base6 = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "mczielinski/bitcoin-historical-data",
    file_path
)

# Mostrar las primeras 5 filas
base6.head()

/tmp/ipykernel_2433/1546421636.py:12: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  base6 = kagglehub.load_dataset(

Using Colab cache for faster access to the 'bitcoin-historical-data' dataset.

    Timestamp  Open  High   Low  Close  Volume
0  1325376060  4.58  4.58  4.58   4.58     0.0
1  1325376120  4.58  4.58  4.58   4.58     0.0
2  1325376180  4.58  4.58  4.58   4.58     0.0
3  1325376240  4.58  4.58  4.58   4.58     0.0
4  1325376300  4.58  4.58  4.58   4.58     0.0

### Verificación

In [112]:
# Ver las primeras 5 filas
base6.head()

    Timestamp  Open  High   Low  Close  Volume
0  1325376060  4.58  4.58  4.58   4.58     0.0
1  1325376120  4.58  4.58  4.58   4.58     0.0
2  1325376180  4.58  4.58  4.58   4.58     0.0
3  1325376240  4.58  4.58  4.58   4.58     0.0
4  1325376300  4.58  4.58  4.58   4.58     0.0

In [113]:
# Ver las últimas 10 filas
base6.tail(10)

          Timestamp      Open      High       Low     Close    Volume
7707208  1787808540  78652.99  78652.99  78642.00  78647.11  0.052243
7707209  1787808600  78649.65  78663.49  78649.65  78663.49  0.747069
7707210  1787808660  78663.37  78663.37  78620.54  78629.16  1.236897
7707211  1787808720  78635.23  78635.23  78631.35  78635.22  0.137061
7707212  1787808780  78635.22  78635.22  78619.44  78625.64  0.349425
7707213  1787808840  78625.63  78626.59  78599.72  78617.34  2.080300
7707214  1787808900  78619.57  78619.57  78582.81  78598.75  2.465185
7707215  1787808960  78607.33  78625.58  78593.00  78625.58  3.162450
7707216  1787809020  78625.57  78656.20  78625.57  78652.90  0.412945
7707217  1787809080  78652.90  78690.58  78652.90  78690.58  0.192006

In [114]:
# Ver 3 filas aleatorias
base6.sample(3)

          Timestamp      Open      High       Low     Close    Volume
3632866  1543348020   3714.81   3719.09   3711.99   3712.38  5.299990
2140972  1453834380    393.46    393.46    392.44    392.44  1.449682
5003552  1625589180  33881.07  33912.98  33881.07  33906.86  1.038047

In [115]:
# Pídale que muestre de la fila 2 a la 5 y solamente la segunda columna
base6.iloc[2:6, [1]]

   Open
2  4.58
3  4.58
4  4.58
5  4.58

In [116]:
# Número de filas
len(base6)

7707218

In [117]:
# Número de filas y columnas
base6.shape

(7707218, 6)

In [118]:
# Nombre de las columnas
base6.columns

Index(['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [119]:
# Tipo de datos
base6.dtypes

Timestamp      int64
Open         float64
High         float64
Low          float64
Close        float64
Volume       float64
dtype: object

In [120]:
 # Información general
base6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7707218 entries, 0 to 7707217
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   Timestamp  int64
 1   Open       float64
 2   High       float64
 3   Low        float64
 4   Close      float64
 5   Volume     float64
dtypes: float64(5), int64(1)
memory usage: 352.8 MB