## **1. Importe todas las librerías que vaya a utilizar.**

In [105]:
# Importar Librerias
import os
import numpy as np
import pandas as pd
from pathlib import Path

## **2. Mejore la visualización de los dataframes como se ha visto en clase.**

In [106]:
## Mejorar la visualización ##
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## **3. Conéctese a su Google Drive y establezca la ruta de los datasets.**

In [107]:
# Conectar con Drive
from google.colab import drive, files
drive.mount('/content/drive')

os.chdir("/content/drive/MyDrive/Curso_IA_20262/GEIH_2026")
ruta = Path("/content/drive/MyDrive/Curso_IA_20262/GEIH_2026")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **4. Cargue los datos en el notebook.**

In [108]:
# Llaves de identificación
llaves_hogar = ["DIRECTORIO", "SECUENCIA_P"]
llaves_persona = ["DIRECTORIO", "SECUENCIA_P", "ORDEN"]

# Diccionario para guardar las bases de cada mes
bases_mensuales = {}

In [109]:
# Recorrer las carpetas de cada mes
for carpeta in ruta.iterdir():

    caracteristicas = None
    hogar = None
    fuerza = None
    ocupados = None

    # Buscar y cargar los archivos
    for archivo in carpeta.glob("*.CSV"):

        nombre = archivo.name.lower()

        if "caracter" in nombre:
            caracteristicas = pd.read_csv(archivo, sep=";", decimal=',', encoding = "latin-1", dtype = str)

        elif "datos del hogar" in nombre:
            hogar = pd.read_csv(archivo, sep=";", decimal=',', encoding = "latin-1", dtype = str)

        elif "fuerza" in nombre:
            fuerza = pd.read_csv(archivo, sep=";", decimal=',', encoding = "latin-1", dtype = str)

        elif "ocupados" in nombre and "no ocupados" not in nombre:
            ocupados = pd.read_csv(archivo, sep=";", decimal=',', encoding = "latin-1", dtype = str)



    # Unir información del hogar
    columnas_hogar = llaves_hogar + [col for col in hogar.columns if col not in caracteristicas.columns]
    base_mes = caracteristicas.merge(hogar[columnas_hogar], on=llaves_hogar, how="left")


    # Unir fuerza de trabajo
    columnas_fuerza = llaves_persona + [col for col in fuerza.columns if col not in base_mes.columns]
    base_mes = base_mes.merge(fuerza[columnas_fuerza], on=llaves_persona, how="left")


    # Unir ocupados
    columnas_ocupados = llaves_persona + [col for col in ocupados.columns if col not in base_mes.columns]
    base_mes = base_mes.merge(ocupados[columnas_ocupados], on=llaves_persona, how="left")


    # Guardar la base resultante
    bases_mensuales[carpeta.name] = base_mes

## **5. Para cada mes de 2026, construya una base de datos uniendo la información**

In [110]:
# Bases unificadas por mes
for mes, df in bases_mensuales.items():
    print("\n", mes)
    print("Dimensiones:", df.shape)
    display(df.head())

 CSV_Febrero
Dimensiones: (67736, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260209,02,2026,8504104,1,1,1,10,NaN,2,45.547661129,08,1,1,1,53,3,1972,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,2,1,1,1,58000,4,4,4,4,4,4,4,4,1,2,NaN,3,1,NaN,NaN,NaN,2,1,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143,1,2,2,12,2,4,1,2395,2,2,1,2,1,NaN,1,1,9,1,1,NaN,2,1900000,2,NaN,2,NaN,NaN,2,NaN,1,300000,2,NaN,2,NaN,2,NaN,NaN,9,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,1,1900000,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,2,8,NaN,1,NaN,1,1,1,14,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,1,10,6121,145,4,50000,1,2,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,4,NaN,1,2250000,01,0143,9211,168
1,20260209,02,2026,8504104,1,2,1,10,NaN,2,45.547661129,08,1,2,2,39,9,1986,2,2,NaN,3,NaN,2,2,1,6,NaN,NaN,2,1,1,1,3,NaN,NaN,4,4,3,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,1,2,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,2,NaN,NaN,2,2,NaN,NaN,NaN,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20260209,02,2026,8504104,1,3,1,10,NaN,2,45.547661129,08,1,3,1,19,10,2006,3,1,2,2,NaN,1,NaN,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,2,1,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,2,NaN,NaN,2,2,NaN,NaN,NaN,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260209,02,2026,8504104,1,4,1,10,NaN,2,45.547661129,08,1,4,2,17,5,2008,3,1,2,2,NaN,2,2,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,5,1,NaN,1,NaN,NaN,NaN,NaN,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260209,02,2026,8504104,1,5,1,10,NaN,2,45.547661129,08,1,5,1,15,3,2010,3,1,2,2,NaN,1,NaN,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,3,3,3,1,1,1,4,3,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 CSV_Abril
Dimensiones: (67349, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260418,04,2026,8567919,1,1,1,10,NaN,2,51.927846885,08,1,1,1,42,8,1983,1,2,NaN,2,NaN,1,NaN,2,6,NaN,NaN,2,1,2,1,1,1,70036,4,4,4,4,4,4,4,4,1,2,NaN,5,1,NaN,1,NaN,2,1,1,2,1,2,1,1,1,1,1,3,1,1,3,2,1,1,1,1,1,3,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4290,1,2,2,12,1,NaN,1,NaN,2,2,1,2,1,NaN,1,1,9,1,1,NaN,2,2000000,2,NaN,2,NaN,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,1,250000,1,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,1,1423500,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,8,4,NaN,1,NaN,1,1,1,5,1,1,1,0,120,4,NaN,3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,1,NaN,60,8,NaN,1,2000000,42,4290,7126,12
1,20260418,04,2026,8567919,1,2,1,10,NaN,2,51.927846885,08,1,2,2,30,4,1995,2,2,NaN,2,NaN,1,NaN,2,6,NaN,NaN,2,1,1,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,1,2,1,2,1,2,1,1,1,1,1,3,1,1,3,2,1,1,1,1,1,3,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,1,NaN,1,4,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4711,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,3,1,1,1,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30000,1,0,30000,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,2,2,30000,1,50000,3,NaN,1,NaN,2,2,60,NaN,NaN,60,NaN,NaN,1,1,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,2,1,1,14,NaN,NaN,3,NaN,1,30000,47,4711,5223,2
2,20260418,04,2026,8567919,1,3,1,10,NaN,2,51.927846885,08,1,2,2,17,12,2008,3,1,2,1,1,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,5,1,NaN,1,NaN,NaN,NaN,NaN,2,1,2,1,1,1,1,1,3,1,1,3,2,1,1,1,1,1,3,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260418,04,2026,8567919,1,4,1,10,NaN,2,51.927846885,08,1,2,1,14,5,2011,3,1,2,1,1,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,4,2,NaN,NaN,NaN,NaN,NaN,NaN,2,1,2,1,1,1,1,1,3,1,1,3,2,1,1,1,1,1,3,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260418,04,2026,8567919,1,5,1,10,NaN,2,51.927846885,08,1,2,1,10,9,2015,3,1,2,1,1,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,2,3,3,NaN,NaN,NaN,NaN,NaN,NaN,2,1,2,1,1,1,1,1,3,1,1,3,2,1,1,1,1,1,3,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 CSV_Mayo
Dimensiones: (67065, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260522,05,2026,8595945,1,1,1,10,NaN,2,80.313778491,08,1,1,2,48,3,1978,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,2,1,1,5,NaN,4,4,4,4,4,4,4,4,1,2,NaN,3,5,NaN,NaN,NaN,1,2,1,1,1,2,1,1,2,2,2,NaN,1,1,3,1,2,1,4,1,1,4,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,NaN,1,4,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4722,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,3,1,1,1,6,NaN,NaN,1200000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450000,1,3600000,3,NaN,6,NaN,2,8,24,2,NaN,24,NaN,NaN,1,1,NaN,3,NaN,2,NaN,NaN,NaN,2,2,1,60,72,4,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,3,NaN,1,450000,47,4722,5221,8
1,20260522,05,2026,8595945,1,2,1,10,NaN,2,80.313778491,08,1,2,1,66,4,1960,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,1,1,1,5,NaN,4,4,4,4,4,4,4,4,2,2,NaN,1,0,NaN,NaN,NaN,2,1,1,1,1,2,1,1,2,2,2,NaN,1,1,3,1,2,1,4,1,1,4,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4290,1,1,NaN,NaN,1,NaN,1,NaN,2,2,2,2,1,NaN,1,1,1,1,1,NaN,2,1200000,2,NaN,2,NaN,NaN,2,NaN,1,300000,2,NaN,2,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,56,NaN,NaN,56,NaN,NaN,7,8,NaN,3,NaN,2,NaN,NaN,NaN,2,2,1,1,48,1,NaN,5,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,5,3,NaN,1,1500000,42,4290,5414,60
2,20260522,05,2026,8595946,1,1,1,10,NaN,2,111.89917688,08,1,1,1,43,8,1982,1,2,NaN,2,NaN,1,NaN,2,6,NaN,NaN,4,NaN,NaN,1,1,1,70036,4,4,4,4,4,4,4,4,1,2,NaN,3,4,NaN,NaN,NaN,2,1,1,3,1,2,1,1,2,2,2,NaN,1,1,1,1,2,1,4,1,1,4,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4111,1,2,1,NaN,1,NaN,1,NaN,2,2,1,2,1,NaN,1,1,1,1,1,NaN,2,2000000,2,NaN,2,NaN,NaN,2,NaN,1,300000,2,NaN,2,NaN,2,NaN,NaN,1,250000,1,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,1,1423500,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,10,8,NaN,1,NaN,1,1,1,10,1,1,1,0,12,1,NaN,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,2,NaN,1,2300000,41,4111,5414,120
3,20260522,05,2026,8595946,1,2,1,10,NaN,2,111.89917688,08,1,2,1,18,1,2008,3,2,NaN,1,1,1,NaN,1,6,NaN,NaN,6,NaN,NaN,1,1,5,NaN,4,4,4,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,2,1,1,3,1,2,1,1,2,2,2,NaN,1,1,1,1,2,1,4,1,1,4,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260522,05,2026,8595947,1,1,1,10,NaN,2,92.70902123,08,1,1,2,31,6,1994,1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,4,NaN,NaN,2,NaN,NaN,NaN,4,4,4,3,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,1,2,1,1,1,2,1,1,2,2,2,NaN,1,1,2,1,2,1,4,1,1,4,4,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,NaN,1,4,NaN,NaN,2,1,6,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1,3,3,3,6,NaN,NaN,100000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90000,1,2700000,1,NaN,4,NaN,1,3,10,2,NaN,0,6,NaN,2,2,NaN,5,NaN,2,NaN,NaN,NaN,2,2,1,12,48,3,NaN,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2,2,1,3,NaN,5,3,NaN,1,90000,01,0145,5230,3

 CSV_Marzo
Dimensiones: (66909, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260313,03,2026,8533530,1,1,1,10,NaN,2,77.703012763,08,1,1,1,22,8,2003,1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,1,1,2,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,3,4,NaN,NaN,NaN,2,1,1,3,1,2,1,0,2,2,2,NaN,2,1,1,1,6,NaN,4,3,5,5,4,NaN,NaN,NaN,150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,3,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141,1,1,NaN,NaN,1,NaN,2,NaN,2,2,2,2,7,NaN,2,2,2,2,1,NaN,2,1000000,2,NaN,2,NaN,NaN,1,60000,1,150000,2,NaN,2,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,60,NaN,NaN,60,NaN,NaN,2,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,0,12,3,NaN,3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,1,2,1,1,2,2,2,1,2,2,NaN,2,1,2,2,2,2,1,2,14,NaN,NaN,3,NaN,1,1210000,01,0141,9213,4
1,20260313,03,2026,8533530,1,2,1,10,NaN,2,77.703012763,08,1,2,2,18,9,2007,2,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,1,1,1,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,4,2,NaN,NaN,NaN,1,2,1,3,1,2,1,0,2,2,2,NaN,2,1,1,1,6,NaN,4,3,5,5,4,NaN,NaN,NaN,150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,3,NaN,1,1,4,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20260313,03,2026,8533530,1,3,1,10,NaN,2,77.703012763,08,1,2,1,0,5,2025,3,1,2,1,1,1,NaN,1,6,NaN,NaN,NaN,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,2,1,0,2,2,2,NaN,2,1,1,1,6,NaN,4,3,5,5,4,NaN,NaN,NaN,150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260313,03,2026,8533531,1,1,1,10,NaN,2,81.12605795,08,1,1,2,47,8,1978,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,2,1,3,NaN,NaN,4,4,4,4,4,4,4,4,2,2,NaN,1,0,NaN,NaN,NaN,1,2,1,1,1,2,2,NaN,2,2,2,NaN,2,1,5,4,6,NaN,4,9,5,5,4,NaN,NaN,NaN,200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,5,NaN,1,1,4,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260313,03,2026,8533531,1,2,1,10,NaN,2,81.12605795,08,1,2,1,47,4,1978,2,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,1,1,3,NaN,NaN,4,4,4,4,4,4,4,4,2,2,NaN,1,0,NaN,NaN,NaN,2,1,1,1,1,2,2,NaN,2,2,2,NaN,2,1,5,4,6,NaN,4,9,5,5,4,NaN,NaN,NaN,200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,5,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,1,1,1,6,NaN,NaN,300000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250000,1,3000000,3,NaN,10,NaN,2,12,50,NaN,NaN,50,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,30,8,NaN,1,250000,01,0161,9211,360

 CSV_Junio
Dimensiones: (66285, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260626,06,2026,8623826,1,1,1,10,NaN,2,36.875978381,08,1,1,1,42,3,1984,1,2,NaN,2,NaN,2,2,2,6,NaN,NaN,3,1,2,1,1,1,70036,4,4,4,4,4,4,4,4,1,2,NaN,8,3,212,5,212,2,1,1,1,1,4,1,1,1,1,1,3,1,1,4,3,1,1,1,1,1,3,1,NaN,NaN,60000000,500000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7310,1,2,1,NaN,1,NaN,1,NaN,1,2,1,1,1,NaN,1,1,1,1,1,NaN,2,1750000,2,NaN,2,NaN,NaN,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,1,249095,2,1,144000,2,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,1,1300000,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,5,7,NaN,1,NaN,1,1,1,13,1,1,1,1,24,4,NaN,3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,11,NaN,20,3,NaN,1,1750000,73,7310,2166,156
1,20260626,06,2026,8623826,1,2,1,10,NaN,2,36.875978381,08,1,2,2,41,8,1984,2,2,NaN,2,NaN,2,2,2,6,NaN,NaN,3,1,1,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,1,2,1,1,1,4,1,1,1,1,1,3,1,1,4,3,1,1,1,1,1,3,1,NaN,NaN,60000000,500000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4761,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,3,1,1,1,6,NaN,NaN,1800000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,700000,1,8400000,3,NaN,6,NaN,2,12,48,NaN,NaN,48,NaN,NaN,1,1,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,3,NaN,1,700000,47,4761,1420,60
2,20260626,06,2026,8623826,1,3,1,10,NaN,2,36.875978381,08,1,3,2,18,8,2007,3,1,2,1,1,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,9,3,419,2,NaN,1,2,1,1,1,4,1,1,1,1,1,3,1,1,4,3,1,1,1,1,1,3,1,NaN,NaN,60000000,500000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260626,06,2026,8623826,1,4,1,10,NaN,2,36.875978381,08,1,2,2,13,6,2012,3,1,2,1,1,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,4,3,NaN,NaN,NaN,NaN,NaN,NaN,1,1,4,1,1,1,1,1,3,1,1,4,3,1,1,1,1,1,3,1,NaN,NaN,60000000,500000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260626,06,2026,8623827,1,1,1,10,NaN,2,43.983790738,08,1,1,1,63,6,1963,1,3,NaN,3,NaN,2,2,2,6,NaN,NaN,2,1,2,1,3,NaN,NaN,4,4,3,4,4,4,4,4,1,2,NaN,4,2,NaN,NaN,NaN,2,1,1,1,1,4,1,1,2,1,1,3,1,1,5,3,1,1,1,1,1,4,5,NaN,NaN,NaN,400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3290,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,1,1,1,6,NaN,NaN,1000000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000000,1,6000000,3,NaN,1,NaN,2,12,40,NaN,NaN,40,NaN,NaN,1,1,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,3,NaN,1,1000000,32,3290,7314,360

 CSV_Enero
Dimensiones: (66606, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260105,01,2026,8473909,1,1,1,10,NaN,2,41.338482381,08,1,1,2,34,3,1991,1,2,NaN,2,NaN,2,2,2,6,NaN,NaN,2,1,2,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,4,3,NaN,NaN,NaN,1,2,1,1,1,1,1,0,2,2,2,NaN,1,1,2,1,2,1,3,1,4,1,5,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,1,NaN,1,4,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4792,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,3,1,1,1,6,NaN,NaN,400000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100000,1,1200000,3,NaN,3,NaN,2,12,28,2,NaN,28,NaN,NaN,1,5,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,0,24,4,NaN,9,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,20,3,NaN,1,100000,47,4792,3322,60
1,20260105,01,2026,8473909,1,2,1,10,NaN,2,41.338482381,08,1,2,1,49,4,1976,2,3,NaN,2,NaN,2,2,2,6,NaN,NaN,2,1,1,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,3,5,NaN,NaN,NaN,2,1,1,1,1,1,1,0,2,2,2,NaN,1,1,2,1,2,1,3,1,4,1,5,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9522,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,3,1,1,1,6,NaN,NaN,2000000,1,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900000,1,22700000,3,NaN,1,NaN,1,12,40,NaN,NaN,40,NaN,NaN,1,2,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,11,NaN,20,3,NaN,1,1900000,95,9522,7412,256
2,20260105,01,2026,8473909,1,3,1,10,NaN,2,41.338482381,08,1,3,2,17,7,2008,3,1,1,1,2,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,5,1,NaN,1,NaN,NaN,NaN,NaN,1,1,1,1,0,2,2,2,NaN,1,1,2,1,2,1,3,1,4,1,5,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260105,01,2026,8473909,1,4,1,10,NaN,2,41.338482381,08,1,1,1,15,8,2010,3,1,1,1,2,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,4,3,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,0,2,2,2,NaN,1,1,2,1,2,1,3,1,4,1,5,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260105,01,2026,8473909,1,5,1,10,NaN,2,41.338482381,08,1,1,1,12,2,2013,3,1,1,1,2,2,2,2,6,NaN,NaN,6,NaN,NaN,1,3,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,4,0,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,0,2,2,2,NaN,1,1,2,1,2,1,3,1,4,1,5,NaN,NaN,NaN,300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **6. Concatene las bases de todos los meses**

In [111]:
# Concatenar las bases de todos los meses
base_geih_2026 = pd.concat(bases_mensuales.values(), ignore_index=True)

# Ver las dimensiones y las primeras filas
print("Dimensiones:", base_geih_2026.shape)
display(base_geih_2026.head())

Dimensiones: (401950, 318)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P3363S1,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3560,P3561,P3067,P3067S1,P3067S2,P6775,P3068,P3562,P3563,P6750,P3073,P550,P6780,P6780S1,P1879,P1879S1,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,P6426
0,20260209,02,2026,8504104,1,1,1,10,NaN,2,45.547661129,08,1,1,1,53,3,1972,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2,1,2,1,1,1,58000,4,4,4,4,4,4,4,4,1,2,NaN,3,1,NaN,NaN,NaN,2,1,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143,1,2,2,12,2,4,1,2395,2,2,1,2,1,NaN,1,1,9,1,1,NaN,2,1900000,2,NaN,2,NaN,NaN,2,NaN,1,300000,2,NaN,2,NaN,2,NaN,NaN,9,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,2,NaN,NaN,1,1900000,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,2,8,NaN,1,NaN,1,1,1,14,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,1,10,6121,145,4,50000,1,2,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,14,NaN,NaN,4,NaN,1,2250000,01,0143,9211,168
1,20260209,02,2026,8504104,1,2,1,10,NaN,2,45.547661129,08,1,2,2,39,9,1986,2,2,NaN,3,NaN,2,2,1,6,NaN,NaN,2,1,1,1,3,NaN,NaN,4,4,3,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,1,2,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,2,NaN,NaN,2,2,NaN,NaN,NaN,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20260209,02,2026,8504104,1,3,1,10,NaN,2,45.547661129,08,1,3,1,19,10,2006,3,1,2,2,NaN,1,NaN,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1,2,NaN,5,2,NaN,2,NaN,2,1,1,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,NaN,1,2,NaN,NaN,2,2,NaN,NaN,NaN,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260209,02,2026,8504104,1,4,1,10,NaN,2,45.547661129,08,1,4,2,17,5,2008,3,1,2,2,NaN,2,2,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1,1,1,5,1,NaN,1,NaN,NaN,NaN,NaN,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260209,02,2026,8504104,1,5,1,10,NaN,2,45.547661129,08,1,5,1,15,3,2010,3,1,2,2,NaN,1,NaN,1,6,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,3,3,3,1,1,1,4,3,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,1,0,2,2,2,NaN,2,1,3,2,2,1,4,8,5,5,4,NaN,NaN,NaN,300000,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,1,3,NaN,NaN,2,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **7. Dataframe 2025-01-14 Correlativa CIIU Rev4.xlsx**

In [113]:
# Leer la tabla de correspondencia CIIU
archivo_ciiu = ruta.parent / "2025-01-14 Correlativa CIIU Rev4.xlsx"
ciiu = pd.read_excel(archivo_ciiu, sheet_name="CIIU 2022", dtype=str)

# Seleccionar código y descripción
ciiu = ciiu[["RAMA4D_R4", "DESCRIPCION_CIIU"]]

# Agregar la descripción CIIU a la base
base_geih_2026 = base_geih_2026.merge(ciiu, on="RAMA4D_R4", how="left")

# Verificar las dimensiones
print("Dimensiones:", base_geih_2026.shape)

# Verificar 10 observaciones aleatorias con código y descripción CIIU
print("\n10 observaciones aleatorias:")
display(
    base_geih_2026[
        ["RAMA4D_R4", "DESCRIPCION_CIIU"]
    ].dropna().sample(10, random_state=42)
)

Dimensiones: (401950, 319)

10 observaciones aleatorias:

       RAMA4D_R4                                   DESCRIPCION_CIIU
330990      8121             Limpieza general interior de edificios
206508      5611           Expendio a la mesa de comidas preparadas
351491      5630  Expendio de bebidas alcohólicas para el consum...
197853      5619  Otros tipos de expendio de comidas preparadas ...
259404      8621  Actividades de la práctica médica, sin interna...
273662      8220   Actividades de centros de llamadas (call center)
401284      4789  Comercio al por menor de otros productos en pu...
229179      0722        Extracción de oro y otros metales preciosos
224821      8610  Actividades de hospitales y clínicas, con inte...
192306      6820  Actividades inmobiliarias realizadas a cambio ...

## **8. Dataframe 2025-01-14 Divipola.xlsx**

In [116]:
# Leer la tabla de departamentos de DIVIPOLA
archivo_divipola = ruta.parent / "2025-01-14 DIVIPOLA.xlsx"
divipola = pd.read_excel(archivo_divipola, sheet_name="Departamentos", header=9, dtype=str)

# Seleccionar código y nombre del departamento
divipola = divipola[["Código", "Nombre"]]

# Renombrar las columnas para hacer el cruce con la base
divipola = divipola.rename(columns={"Código": "DPTO", "Nombre": "NOMBRE_DPTO"})

# Agregar el nombre del departamento a la base
base_geih_2026 = base_geih_2026.merge(divipola, on="DPTO", how="left")

# Verificar las dimensiones
print("Dimensiones:", base_geih_2026.shape)

# Verificar 10 departamentos aleatorios
print("\n10 departamentos aleatorios:")
display(
    base_geih_2026[
        ["DPTO", "NOMBRE_DPTO"]
    ].dropna().drop_duplicates().sample(10, random_state=42)
)

Dimensiones: (401950, 320)

10 departamentos aleatorios:

      DPTO         NOMBRE_DPTO
15241   97              VAUPÉS
2596    27               CHOCÓ
14649   86            PUTUMAYO
5065    15              BOYACÁ
1348    54  NORTE DE SANTANDER
1380    52              NARIÑO
7431    23             CÓRDOBA
8393    41               HUILA
1951    73              TOLIMA
0       08           ATLÁNTICO

## **9. Guarde la base de la GEIH 2026 en un archivo csv.**

In [118]:
# Guardar la base GEIH 2026 como CSV
archivo_salida = ruta.parent / "Base_GEIH_2026.csv"
base_geih_2026.to_csv(archivo_salida, index=False, encoding="utf-8")

# Verificar que el archivo fue guardado
print("Base guardada en:", archivo_salida)
print("Dimensiones:", base_geih_2026.shape)

Base guardada en: /content/drive/MyDrive/Curso_IA_20262/Base_GEIH_2026.csv
Dimensiones: (401950, 320)